# Replace the text below to customize your site
site_name: Nicolò Baldi - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Nicolò Baldi
copyright: Copyleft 2023 "Nicolò Baldi" - GNU Free Documentation License
repo_name: 'MDEF Repository'
site_url: https://niente010.github.io/MDEF_website/
repo_url: 'https://github.com/niente010/MDEF_website'


nav:
  - Home: index.md
  - About: about/me.md
  - Master Project:
      - Initial Ideas: project/project.md
  - Reflections :
      - Term 1:
          - Landing: term1/Landing.md
          - AoWS: term1/AtlasOfWeakSignals.md
          - Design Studio 01: term1/DesignStudio01.md
          - Documenting Design: term1/DocumentingDesign.md

extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: "https://www.instagram.com/nicolo.baldi_/"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/nicol%C3%B2baldi"
    - icon: fontawesome/brands/github
      link: "https://github.com/niente010"

theme:
  name: material
  palette:
    scheme: slate
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
  font:
    # See available fonts at https://fonts.google.com/
    text: JetBrains Mono
    code: Cutive Mono
    logo: images/LOGO.png
  favicon: images/LOGO.png
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
 # - glightbox


markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - attr_list
  - tables
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
