# Replace the text below to customize your site
site_name: Nicolò Baldi - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Nicolò Baldi
copyright: Copyleft 2023 "Nicolò Baldi" - GNU Free Documentation License
repo_name: 'MDEF Repository'
site_url: https://niente010.github.io/MDEF_website/
repo_url: 'https://github.com/niente010/MDEF_website'


nav:
  - Home: index.md
  - About: about/me.md
  - Reflections:
      - Term 1:
          - Landing: term1/Landing.md
          - Documenting Design: term1/DocumentingDesign.md
          - Atlas of Weak Signals: term1/AtlasOfWeakSignals.md
          - Design Studio 01: term1/DesignStudio01.md
          - The Machine Paradox: term1/TheMachineParadox.md
          - Living With Your Own Ideas: term1/LivingWithYourOwnIdeas.md
          - Biology Zero: term1/BioZero.md
          - Agriculture Zero: term1/AgriZero.md
          - Design With Others: term1/DesignWithOthers.md
          - Extended Intelligences: term1/ExtendedIntelligences.md
      - Term 2:
          - Design Studio 02: term2/DesignStudio02.md
          - Designing in a State of Climate Emergency: term2/DesigningInAStateOfClimateEmergency.md
          - Digital Prototyping: term2/DigitalPrototyping.md
          - Communicating Ideas: term2/CommunicatingIdeas.md
          - Design for Collective Intelligence: term2/DesignCollectiveIntelligence.md
          - Measuring the World: term2/MeasuringTheWorld.md
          - Extended Intelligences II: term2/ExtendedIntelligencesII.md
  - Master Thesis:
    - Tandem project: project/tandemproject.md
    - ooorganismooo: project/ooorganismooo.md

extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: "https://www.instagram.com/nicolo.baldi_/"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/nicol%C3%B2baldi"
    - icon: fontawesome/brands/github
      link: "https://github.com/niente010"

theme:
  name: material
  palette:
    scheme: slate
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
  font:
    # See available fonts at https://fonts.google.com/
    text: JetBrains Mono
    code: Cutive Mono
  logo: images/NB_LogoIcon.png
  favicon: images/NB_LogoIcon.png
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.code.copy

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox:
      zoomable: true
      draggable: true
      skip_classes:
        - skip-lightbox
          
markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format  
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - attr_list
  - tables
  - pymdownx.tabbed
  
extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
